Vagrant.configure("2") do |config|
    config.vm.box = "tranphuquy19/ubuntu2204desktop-k3d-k8s-docker"
    config.vm.network "private_network", ip: "192.168.10.102"
    config.vm.hostname = "worker2.xtl"
  
    config.vm.provider "virtualbox" do |vb|
       vb.name = "worker2.xtl"
       vb.cpus = 1
       vb.memory = "1024"
    end
  
    # Chạy các lệnh shell
    config.vm.provision "shell", inline: <<-SHELL
      # Đặt pass 123 có tài khoản root và cho phép SSH
      echo "123" | passwd --stdin root
      sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
      systemctl reload sshd
  # Ghi nội dung sau ra file /etc/hosts để truy cập được các máy theo HOSTNAME
cat >>/etc/hosts<<EOF
192.168.10.100 master.xtl
192.168.10.101 worker1.xtl
192.168.10.102 worker2.xtl
EOF
  
    SHELL
end