apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  ports:
  - port: '{{ .Values.mongodb.servicePort | int }}'
    targetPort: '{{ .Values.mongodb.containerPort | int }}'
  selector:
    app: mongodb
