apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: '{{ .Values.eurekaServer.hpaName }}'
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: '{{ .Values.eurekaServer.deploymentName }}'
  minReplicas: 1
  maxReplicas: 5
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: '{{ .Values.eurekaServer.hpaCpuUtilization }}'
