apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: '{{ .Values.eurekaServer.hpaName }}'
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: '{{ .Values.eurekaServer.deploymentName }}'
  minReplicas: '{{ .Values.eurekaServer.hpaMinReplicas | int}}'
  maxReplicas: '{{ .Values.eurekaServer.hpaMaxReplicas | int}}'
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: '{{ .Values.eurekaServer.hpaCpuUtilization }}'
