---
apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.eurekaServer.serviceName }}'
spec:
  type: '{{ .Values.eurekaServer.serviceType }}'
  ports:
    - port: 8761
      targetPort: 8761
      nodePort: 30001
  selector:
    app: eureka-server
