apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.eurekaServer.serviceName }}'
spec:
  type: '{{ .Values.eurekaServer.serviceType }}'
  ports:
  - port: '{{ .Values.eurekaServer.servicePort | int }}'
    targetPort: '{{ .Values.eurekaServer.containerPort | int }}'
    nodePort: '{{ .Values.eurekaServer.nodePort | int }}'
  selector:
    app: eureka-server
