apiVersion: apps/v2
kind: Deployment
metadata:
  name: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
      - name: eureka-server
        image: quockhanh107/eureka-server:latest
        ports:
        - containerPort: 8761
        env:
        - name: JAVA_OPTS
          value: "-Deureka.instance.preferIpAddress=true"
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "300m"
