apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.eurekaServer.serviceName }}'
spec:
  type: '{{ .Values.eurekaServer.serviceType }}'
  ports:
  - port: '{{ .Values.eurekaServer.servicePort }}'
    targetPort: '{{ .Values.eurekaServer.containerPort }}'
    nodePort: '{{ .Values.eurekaServer.nodePort }}'
  selector:
    app: eureka-server
