apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.movieService.serviceName }}'
spec:
  type: '{{ .Values.movieService.serviceType }}'
  ports:
  - port: '{{ .Values.movieService.servicePort | int }}'
    targetPort: '{{ .Values.movieService.containerPort | int }}'
    nodePort: '{{ .Values.movieService.nodePort }}''
  selector:
    app: movie-service
