apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: movie-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: movie-service
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 120 
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 120  
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60
      - type: Percent
        value: 30
        periodSeconds: 60
