apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.movieService.deploymentName }}
spec:
  replicas: {{ .Values.movieService.replicaCount }}
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
      - name: movie-service
        image: {{ .Values.movieService.image }}
        ports:
        - containerPort: {{ .Values.movieService.containerPort }}
{{- if .Files.Get "movie-service/movie-service-hpa.yaml" }}
{{ .Files.Get "movie-service/movie-service-hpa.yaml" | indent 8 }}
{{- end }}
