# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: {{ .Values.movieService.deploymentName }}
# spec:
#   replicas: {{ .Values.movieService.replicaCount }}
#   selector:
#     matchLabels:
#       app: movie-service
#   template:
#     metadata:
#       labels:
#         app: movie-service
#     spec:
#       containers:
#       - name: movie-service
#         image: {{ .Values.movieService.image }}
#         ports:
#         - containerPort: {{ .Values.movieService.containerPort }}
#         resources:
#           requests:
#             cpu: "100m"
#           limits:
#             cpu: "300m"
#         # livenessProbe:
#         #   httpGet:
#         #     path: /api/movie/movies/healthz
#         #     port: 8080
#         #   initialDelaySeconds: 15
#         #   periodSeconds: 10
#         # # Thêm readinessProbe
#         # readinessProbe:
#         #   httpGet:
#         #     path: /api/movie/movies/healthz
#         #     port: 8080
#         #   initialDelaySeconds: 15
#         #   periodSeconds: 10
#         # # Thêm startupProbe
#         # startupProbe:
#         #   httpGet:
#         #     path: /api/movie/movies/healthz
#         #     port: 8080
#         #   failureThreshold: 30
#         #   periodSeconds: 10
        
# {{- if .Files.Get "movie-service/movie-service-hpa.yaml" }}
# {{ .Files.Get "movie-service/movie-service-hpa.yaml" | indent 8 }}
# {{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Values.movieService.deploymentName }}'
spec:
  replicas: '{{ .Values.movieService.replicaCount }}'
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
      - name: movie-service
        image: '{{ .Values.movieService.image }}'
        ports:
        - containerPort: {{ .Values.movieService.containerPort }}
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "300m"
{{- if .Files.Get "movie-service/movie-service-hpa.yaml" }}
{{ .Files.Get "movie-service/movie-service-hpa.yaml" | indent 8 }}
{{- end }}

