apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.movieService.hpaName }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.movieService.deploymentName }}
  minReplicas: {{ .Values.movieService.hpaMinReplicas }}
  maxReplicas: {{ .Values.movieService.hpaMaxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.movieService.hpaCpuUtilization }}
  
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 5
      policies:
      - type: Pods
        value: 2
        periodSeconds: 5
      - type: Percent
        value: 100
        periodSeconds: 5
    scaleDown:
      stabilizationWindowSeconds: 120  
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60
      - type: Percent
        value: 100
        periodSeconds: 60

