apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.movieService.serviceName }}'
spec:
  type: '{{ .Values.movieService.serviceType }}'
  ports:
  - port: '{{ .Values.movieService.servicePort }}'
    targetPort: '{{ .Values.movieService.containerPort }}'
    nodePort: '{{ .Values.movieService.nodePort }}'
  selector:
    app: movie-service
