apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.serviceName }}
  namespace: default
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: {{ .Values.frontend.servicePort }}
    targetPort: {{ .Values.frontend.containerPort }}
    nodePort: {{ .Values.frontend.nodePort }}
