apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Values.frontend.deploymentName }}'
spec:
  replicas: '{{ .Values.frontend.replicaCount }}'
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: '{{ .Values.frontend.image }}'
        ports:
        - containerPort: 80
