apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loki
  namespace: monitoring
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - loki.quockhanhtech.io.vn
    secretName: loki-quockhanhtech-tls
  rules:
  - host: loki.quockhanhtech.io.vn
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: loki
            port:
                number: 3100
