apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

---
apiVersion: v1
# kind là loại Service
kind: Service
metadata:
  name: nginx-svc
  namespace: default
spec:
  ports:
  # port bên ngoài của pods mà các pods có thể giao tiếp được với nhau
  - port: 80
  # port target với 8080 của deployment
    targetPort: 80
  selector:
  # dựa theo app : nginx-deployment ở labels trên kia sẽ map với service này
    app: nginx
  type: ClusterIP
