Vagrant.configure("2") do |config|
    config.vm.box = "tranphuquy19/ubuntu2204desktop-k3d-k8s-docker"

    config.vm.provider "virtualbox" do |vb|
        vb.cpus = 2
        vb.memory = "8096"
     end
  end