apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: metrics-server-configmap-reader
  namespace: kube-system
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["extension-apiserver-authentication"]
  verbs: ["get"]
