apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metrics-server-configmap-reader-binding
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: metrics-server
  namespace: default
roleRef:
  kind: Role
  name: metrics-server-configmap-reader
  apiGroup: rbac.authorization.k8s.io
