apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.emailService.serviceName }}'
spec:
  type: '{{ .Values.emailService.serviceType }}'
  ports:
  - port: '{{ .Values.emailService.servicePort }}'
    targetPort: '{{ .Values.emailService.containerPort }}'
    nodePort: '{{ .Values.emailService.nodePort }}'
  selector:
    app: email-service
