apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.emailService.serviceName }}'
spec:
  type: '{{ .Values.emailService.serviceType }}'
  ports:
  - port: '{{ .Values.emailService.servicePort | int }}'
    targetPort: '{{ .Values.emailService.containerPort | int }}'
    nodePort: '{{ .Values.emailService.nodePort | int }}'
  selector:
    app: email-service
