---
apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.emailService.serviceName }}'
spec:
  type: '{{ .Values.emailService.serviceType }}'
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30003
  selector:
    app: email-service
