apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.emailService.serviceName }}'
spec:
  type: '{{ .Values.emailService.serviceType }}'
  ports:
  - port: {{ .Values.emailService.servicePort }}
    targetPort: {{ .Values.emailService.containerPort }}
    {{- if eq .Values.emailService.serviceType "NodePort" }}
    nodePort: {{ .Values.emailService.nodePort }}
    {{- end }}
  selector:
    app: email-service
