apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
  - port: '{{ .Values.postgres.servicePort | int }}'
    targetPort: '{{ .Values.postgres.containerPort | int }}'
  selector:
    app: postgres
