---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Values.apiGateway.deploymentName }}'
spec:
  replicas: '{{ .Values.apiGateway.replicaCount }}'
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: '{{ .Values.apiGateway.image }}'
          ports:
            - containerPort: '{{ .Values.apiGateway.containerPort }}'
          env:
            - name: JAVA_OPTS
              value: '{{ .Values.apiGateway.javaOpts }}'
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
