---
apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.apiGateway.serviceName }}'
spec:
  type: '{{ .Values.apiGateway.serviceType }}'
  ports:
    - port: '{{ .Values.apiGateway.servicePort | int }}'
      targetPort: '{{ .Values.apiGateway.containerPort | int }}'
      nodePort: '{{ .Values.apiGateway.nodePort | int }}'
  selector:
    app: api-gateway
