---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: '{{ .Values.apiGateway.hpaName }}'
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: '{{ .Values.apiGateway.deploymentName }}'
  minReplicas: {{.Values.apiGateway.hpaMinReplicas | int}}
  maxReplicas: '{{ .Values.apiGateway.hpaMaxReplicas | int }}'
  metrics:
    - type: Resource
      resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: '{{ .Values.apiGateway.hpaCpuUtilization }}'
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 5
      policies:
        - type: Pods
          value: 2
          periodSeconds: 5
        - type: Percent
          value: 100
          periodSeconds: 5
    scaleDown:
      stabilizationWindowSeconds: 120
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
        - type: Percent
          value: 100
          periodSeconds: 60
