apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Pods
        value: 1
        periodSeconds: 1
      selectPolicy: Min
    scaleDown:
      stabilizationWindowSeconds: 180  
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60
      - type: Percent
        value: 30
        periodSeconds: 60
      selectPolicy: Max
