---
apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.apiGateway.serviceName }}'
spec:
  type: '{{ .Values.apiGateway.serviceType }}'
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 8080
  selector:
    app: api-gateway
