apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.apiGateway.serviceName }}'
spec:
  type: '{{ .Values.apiGateway.serviceType }}'
  ports:
  - port: '{{ .Values.apiGateway.servicePort }}'
    targetPort: '{{ .Values.apiGateway.containerPort }}'
    {{- if eq .Values.apiGateway.serviceType "NodePort" }}
    nodePort: '{{ .Values.apiGateway.nodePort }}'
    {{- end }}
  selector:
    app: api-gateway
