---
apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.apiGateway.serviceName }}'
spec:
  type: '{{ .Values.apiGateway.serviceType }}'
  ports:
    - port: '{{ .Values.apiGateway.servicePort }}'
      targetPort: '{{ .Values.apiGateway.containerPort }}'
      nodePort: '{{ .Values.apiGateway.nodePort }}'
  selector:
    app: api-gateway
