apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.userService.serviceName }}'
spec:
  type: NodePort
  ports:
  - port: '{{ .Values.userService.servicePort | int}}'
    targetPort: '{{ .Values.userService.containerPort | int}}'
    nodePort: '{{ .Values.userService.nodePort | int}}'
  selector:
    app: user-service
