apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Values.userService.deploymentName }}'
spec:
  replicas: '{{ .Values.userService.replicaCount }}'
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: '{{ .Values.userService.image }}'
        ports:
        - containerPort: {{ .Values.userService.containerPort }}
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "300m"
