---
apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.userService.serviceName }}'
spec:
  type: NodePort
  ports:
    - port: 8890
      targetPort: 8890
      nodePort: 30005
  selector:
    app: user-service
