apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.userService.serviceName }}
spec:
  type: NodePort
  ports:
  - port: {{ .Values.userService.servicePort }}
    targetPort: {{ .Values.userService.containerPort }}
    nodePort: {{ .Values.userService.nodePort }}
  selector:
    app: user-service
